#!/usr/bin/php
<?php
function __autoload($name){
    if(substr($name,0,7)=='doczen_'){
        include dirname(__FILE__).'/src/'
                .str_replace('_','/',substr($name,7)).'.php';
    }else{
        return false;
    }
}

if(substr($_SERVER['argv'][1],0,5)=='make-'){
    $doczen_master = new doczen_master;
    $doczen_master->scan($_SERVER['argv'][2]?$_SERVER['argv'][2]:'index.t2t');
    $doczen_master->build(substr($_SERVER['argv'][1],5));
}else{
    switch($_SERVER['argv'][1]){
    
        case 'init':
            doczen_utils::sync_dir(dirname(__FILE__).'/skel', '.');
            break;
    
        default:
            $cmdname = basename($_SERVER['argv'][0]);
            $builder_dir = dirname(__FILE__).'/src/builder';
            $builders = array();
            
            if ($handle = opendir($builder_dir)) {
                while (false !== ($file = readdir($handle))) {
                    if($file{0}!='.' && substr($file,-4,4)=='.php'){
                        include $builder_dir.'/'.$file;
                        if(class_exists('doczen_builder_'.substr($file,0,-4))){
                            $builders[] = substr($file,0,-4);
                        }
                    }
                }
                closedir($handle);
            }
            
            echo "Usage: ".str_repeat("=",40)."\n";
            foreach($builders as $builder){
                echo "\t{$cmdname} make-{$builder}:\n\t\t生成{$builder}格式\n\n";
            }
            echo "\t{$cmdname} init:\n\t\t初始化文档\n\n";
    }
}

#vim:ft=php